In [ ]:
import torch
torch.__version__

'1.10.0+cu111'

In [ ]:
# Creating a  tensor
import numpy as np
A = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
    ])
B = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
    ])

# Tensor addition
print('Addition: \n',A+B)
print('Shape: ',(A+B).shape)

Addition: 
 [[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]
Shape:  (3, 3, 3)


In [ ]:
T1 = torch.tensor(A)
T2 = torch.tensor(B)
print('Tensor T1: \n',T1)
print('Rank of T!: \n',len(T1))
print('Shape of T!: \n',T1.shape)

Tensor T1: 
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]])
Rank of T!: 
 3
Shape of T!: 
 torch.Size([3, 3, 3])


In [ ]:
#Creating tensors
t1 = [1,2,3,4,5,6]
t2 = np.array([1,2,3,4,5,6])

t1 = torch.as_tensor(t1)
t2 = torch.from_numpy(t2)

#Printing tensors
print(t1,'\t',t1.shape)
print(t2,'\t',t2.shape)

tensor([1, 2, 3, 4, 5, 6]) 	 torch.Size([6])
tensor([1, 2, 3, 4, 5, 6]) 	 torch.Size([6])
